name: APK Yapici
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # İşte burası robotun Flutter'ı kurduğu yer
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
      
      # Burası da hatayı düzelten komut
      - run: flutter pub get
      
      # APK'yı pişiren komut
      - run: flutter build apk --release --no-tree-shake-icons
      
      # APK'yı sana sunan komut
      - uses: actions/upload-artifact@v3
        with:
          name: blind-id-apk
          path: build/app/outputs/flutter-apk/app-release.apk
